ADDED getIndex() - GET all Projects and all Clients
Google-Developer-Students-Club-DMCE/project-mgmt-api-hacktober2022 pull request #16
Opened 2022-10-17 16:35 UTC by fallen-ecstasy

Hey @VighneshManjrekar , I have completed and tested the method on the given data.....Kindly test it from your side too, if any problem let me know

Else Please merge this branch.

Issue #2

2022-10-18 02:56 UTC, VighneshManjrekar requested changes
Changes are expected to `controllers/main.controllers.js` file only PR should not contain changes of other files or directories

2022-10-18 02:56 UTC, VighneshManjrekar commented on controllers/main.controllers.js
> +    const clients = await Client.find();
include client reference while fetching projects

2022-10-18 06:50 UTC, fallen-ecstasy commented on controllers/main.controllers.js
> +    const clients = await Client.find();
Okay onto it

2022-10-23 14:03 UTC, VighneshManjrekar commented
Closing this PR since no response from contributor

2022-10-23 14:04 UTC, closed without merging